version: "3"
services:
  app:
    build: ./docker
    container_name: project_app
    volumes:
      - ./:/var/www/html/
      - ./docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db

  db:
    image: percona:5.7
    container_name: project_db
    restart: always
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./var/database/:/var/lib/mysql
    ports:
      - 3339:3306